### PR TITLE
Added backend gulp task to gulp tests build pipeline

### PR DESCRIPTION
**Pull request by kn9ts**

### CODE REVIEW

**Comment by andela-gukpere** [comment]
@kn9ts @andela-totieno e2e and fend tests didn't run in your branch. 
https://circleci.com/gh/andela/vvida/362
Why?

**Comment by kn9ts** [comment]
```
[08:41:19] Using gulpfile ~/vvida/gulpfile.js
[08:41:19] Starting 'test:fend'...
[08:41:19] Starting 'test:bend'...
[08:41:19] Starting 'test:e2e'...
[08:41:19] Starting Karma server...
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
npm ERR! Test failed.  See above for more details.
```

It seems `fend` tests began and an error took place, thus `circle-ci` killed the build on the failure of `fend`

**Comment by andela-gukpere** [comment]
When you run `npm test` on your machine do you get a similar error?

**Comment by kn9ts** [comment]
No. The test actaully run, also noticed the e2e test runs parallel to the fend and bend tests (in my machine). Even if a couple of the resource tests fail, it still runs fine.

**Comment by andela-gukpere** [comment]
@kn9ts @andela-nmartin What happens when you run `npm test` on your machine?

**Pull request closed without merging**
