### PR TITLE
[Fixes #106731208] refactor: renamed schema folder to models and corrected referencing of the models in the app's business logic

### PR DESCRIPTION
**Pull request by kn9ts**

### CODE REVIEW

**Comment by andela-gukpere** [comment]
@kn9ts Too many changes to review, I'll merge the request, you are fully responsible for it's commits :laughing:

**Comment by kn9ts** [comment]
Hahahah!! And many more coming that way. :D

**Comment by andela-bmosigisi** [comment]
Hi,

I found that  article  a couple of days ago and thought  you may  be really  interested in such info,  just  read it  here  <http://clever.isouth.org/e3wnipt>

Sent from a prehistoric stone tablet, brianmosigisi@yahoo.com

**Comment by andela-bmosigisi** [comment]
Hello,

We are waiting for something exciting to happen soon, you're going to  like it! Please read more about it  here <http://care.cheng.ws/e3ououds>

Best wishes, brianmosigisi@yahoo.com

**Pull request merged**
